[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps"]

[phases.build]
cmds = [
  "./node_modules/.bin/tsc -p tsconfig.app.json",
  "./node_modules/.bin/vite build",
  "./node_modules/.bin/tsc -p tsconfig.server.json"
]

[start]
cmd = "node dist-server/server/index.js"
